### ISSUE TITLE
Incorrect footer in "Compare with latest" 

### ISSUE THREAD

**Issue by JayDaley** [ietf-tools/author-tools#465]
### Describe the issue

When "Compare with latest" is used, there is a footer on the output that says 

> This html diff was produced by rfcdiff 1.45. The latest version is available from [http://tools.ietf.org/tools/rfcdiff/](http://www.tools.ietf.org/tools/rfcdiff/)

That link redirects back to https://author-tools.ietf.org/iddiff which is different from advertised.  It would be better to lose that footer entirely or possibly change it to something more detailed.  Happy to provide text for the latter if needed.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by kesara** [comment]
This has been fixed with #559 and https://github.com/ietf-tools/rfcdiff/pull/7
