### ISSUE TITLE
SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by davidi67** [ietf-tools/author-tools#521]
### Describe the issue

Using IETF Author Tools with a markdown file based on 'draft-todo-yourname-protocol.md` . It has compiled perfectly for weeks while I work on revisions, but the exact same file that compiled yesterday now gives me an error:

    SyntaxError: Unexpected token '<', "

This happens using both Chrome and Edge. Has there been some change?

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by kesara** [comment]
@davidi67 This was a configuration error that affected file uploads.
This has been fixed now.
