### ISSUE TITLE
Useless error message

### ISSUE THREAD

**Issue by dnoveck** [ietf-tools/author-tools#522]
### Describe the issue

I am trying to use the author tools to process a 2K-line input file and get the following useless error message:

SyntaxError: Unexpected token '<', "

There is no line number or any other cotext that I can use to find the problem that needs to be fixed.

I've attached my xml file as a text files since .xml is not accepted.

This needs to be fixed right awy.  I am dead in the water.
[draft-dnoveck-nfsv4-acls-05xml.txt](https://github.com/user-attachments/files/16660466/draft-dnoveck-nfsv4-acls-05xml.txt)

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by kesara** [comment]
@dnoveck, This was a configuration issue that affected file uploads.
This has been corrected now.
Sorry for the inconvenience.
