### ISSUE TITLE
Are xml2rfc and  iddiff tools not working this morning?

### ISSUE THREAD

**Issue by ksriram25** [ietf-tools/author-tools#523]
### Describe the issue

xml2rfc (https://author-tools.ietf.org/) gives this error message when I run a .xml file:
SyntaxError: Unexpected token '<', "
Normally it gives a line number and other details for errors.
The same xml file worked fine yesterday and produced .txt file on xml2rfc.

Also, iddiff (https://author-tools.ietf.org/iddiff) tool seems to be misbehaving.  It gives this error when I try to diff two .txt files:
TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.
The same two files worked fine when I did iddiff on them yesterday.

My email: ksriram25@gmail.com  or ksriram@nist.gov

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by kesara** [comment]
@ksriram25, There was a configuration issue that affected file uploads which has been corrected now.
