### ISSUE TITLE
iddiff issue:  "TypeError: Node.appendChild: Argument 1 is not an object." after clicking the Compare button

### ISSUE THREAD

**Issue by lbartholomew-rpc** [ietf-tools/author-tools#524]
### Describe the issue

After uploading two textfiles on <https://author-tools.ietf.org/iddiff> for comparison and clicking "Compare (side by side)", the diff fails and you get "TypeError: Node.appendChild: Argument 1 is not an object."

I've tried this several times over about 10 minutes.  This might be a brief temporary glitch, but reporting it in case it isn't.  Thank you!

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by kesara** [comment]
@lbartholomew-rpc There was a configuration issue that affected file uploads which has been corrected now.

**Comment by lbartholomew-rpc** [comment]
Thank you, Kesara!
