### ISSUE TITLE
submission/idnits test do not check version/give enlightening error message

### ISSUE THREAD

**Issue by sdaoden** [ietf-tools/author-tools#538]
### Describe the issue

I opened
<pre>
[rt5.ietf.org #36331] internet-draft submissions: cancelled due to a system error
</pre>
and Tess Chapeta answered
<pre>
|I believe the issue with your drafts is with version="0". Per, https://
 |authors.ietf.org/en/rfcxml-vocabulary#version, please update this to \
 |version=
 |"3" and try re-uploading both drafts. If the problem persist, please let me
 |know!
</pre>
and indeed it worked after adjustment.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by kesara** [comment]
This has been fixed in upcoming idnits release (v3), which generates the following error similar to this:
```
 2  Error
 └- Code - XML_UNSUPPORTED_VERSION
 └- Desc - The schema version of this document is unsupported.
 └- Path - rfc.version
```
