### ISSUE TITLE
idnits: line number mismatch

### ISSUE THREAD

**Issue by sdaoden** [ietf-tools/author-tools#539]
### Description

Hello.
When i yesterday failed to create a draft submission, i first had to fix an error that idnits reported.
It was complaining on the line length of a sourcecode line in
https://datatracker.ietf.org/doc/draft-nurpmeso-smtp-tls-srv/,
to be exact the last line was not a follow-up of the "signature" one, but it was all one line:
<pre>
body-hash = hash-alg (canon-body, l-param)
data-hash = hash-alg (h-headers, D-SIG, body-hash)
signature = sig-alg (d-domain, selector,
                     data-hash / (h-headers, D-SIG, body-hash))
</pre>
The tool was showing a wrong line number, i think 137 where it should have been 117.
(I first removed some comments around that shown line number, only then realized that another draft passed without problems with the same comments, so then i could search for something "real".)

It would be nice to see (a subset of) the offending line, if getting line numbers right is too hard.
Thank you!

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by kesara** [comment]
Author Tools currently uses idnits v2 by default.
There's a new implementation (still in alpha stage) idnits v3 [^1].
I'll close this issue as we are actively working on the new implementation.
You can test the current version on author tools, as well[^2]. It works better with XML source.

[^1]: https://github.com/ietf-tools/idnits/tree/v3
[^2]: https://author-tools.ietf.org/idnits3
