### ISSUE TITLE
update intro text at https://author-tools.ietf.org/idnits

### ISSUE THREAD

**Issue by ghwood** [ietf-tools/author-tools#543]
### Description

The old text has a number of grammatical nits and old links. New proposed text to address these:

# I-D Diff (iddiff)

This service inspects Internet-Draft (I-D) documents for conditions that should be adjusted to bring the document into line with policies from the IETF, the IETF Trust, and the RFC Editor. Issues are reported based on:

+ [I-D Content Guidelines](https://authors.ietf.org/en/content-guidelines-overview)
+ Additional requirements captured from Area Directors (ADs) and authors over time.
+ Requirements in the [original description of I-D Nits](https://iaoc.ietf.org/documents/idnits-SOW-00.pdf)

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by kesara** [comment]
I'll use the heading as **I-D Nits (idnits)**.
