### ISSUE TITLE
New text for https://author-tools.ietf.org/svgcheck

### ISSUE THREAD

**Issue by ghwood** [ietf-tools/author-tools#544]
### Description

New proposed text to provide a clearer description of the service.

# SVG Checker (svgcheck)

This service checks SVG files against the specification in [RFC7996](https://www.rfc-editor.org/rfc/rfc7996), which is used in RFCs, using [svgcheck](https://github.com/ietf-tools/svgcheck).

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by kesara** [comment]
@ghwood, `svgcheck` uses [RFC 7996 bis](https://datatracker.ietf.org/doc/draft-7996-bis/) specification.

**Comment by kesara** [comment]
#555 updates the text as
> This service checks SVG files against the specification in [draft-7996-bis-00](https://datatracker.ietf.org/doc/draft-7996-bis/), which is used in RFCs, using [svgcheck](https://github.com/ietf-tools/svgcheck).

Happy to change it if this needs more tweaks.
