### ISSUE TITLE
Wrong link to subscribe to IRTF mailing lists

### ISSUE THREAD

**Issue by emanjon** [ietf-tools/author-tools#550]
### Describe the issue

When using "venue:" in markdown, the link to subscribe to the CFRG mailing list is wrong. I assume this applies to all IRTF RGs but I have not checked. When using 

venue:
  group: "Crypto Forum"
  type: "Research Group"
  mail: "cfrg@irtf.org"
  arch: "https://mailarchive.ietf.org/arch/browse/cfrg/"
  github: "sfluhrer/ml-kem-security-considerations"
  latest: "https://sfluhrer.github.io/ml-kem-security-considerations/draft-sfluhrer-cfrg-ml-kem-security-considerations.html"

or

venue:
  group: "Crypto Forum"
  type: "Research Group"
  mail: "cfrg@ietf.org"
  arch: "https://mailarchive.ietf.org/arch/browse/cfrg/"
  github: "sfluhrer/ml-kem-security-considerations"
  latest: "https://sfluhrer.github.io/ml-kem-security-considerations/draft-sfluhrer-cfrg-ml-kem-security-considerations.html"

The following non-existing link is used:

Subscribe at https://www.ietf.org/mailman/listinfo/cfrg/.

The correct link is

https://mailman.irtf.org/mailman/listinfo/cfrg

### Code of Conduct

- [x] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by kesara** [comment]
@emanjon, This is a [kramdown-rfc](https://github.com/cabo/kramdown-rfc/) issue.
